# Generated by Django 4.2.20 on 2025-04-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genmodels", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="capability",
            options={"verbose_name_plural": "capabilities"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "categories"},
        ),
        migrations.AlterModelOptions(
            name="mlmodel",
            options={"verbose_name": "ML Model", "verbose_name_plural": "ML Models"},
        ),
        migrations.AlterModelOptions(
            name="technology",
            options={"verbose_name_plural": "technologies"},
        ),
        migrations.AlterModelOptions(
            name="timetoproduceoutput",
            options={"verbose_name_plural": "times to produce output"},
        ),
        migrations.AlterField(
            model_name="mlmodel",
            name="are_checkpoints_available",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Don't know")],
                default="U",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="mlmodel",
            name="can_finetune",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Don't know")],
                default="U",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="mlmodel",
            name="can_train_from_scratch",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Don't know")],
                default="U",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="mlmodel",
            name="dataset",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="mlmodel",
            name="has_real_time_inference",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Don't know")],
                default="U",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="mlmodel",
            name="interactions",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="mlmodel",
            name="is_free",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Don't know")],
                default="U",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="mlmodel",
            name="is_open_source",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Don't know")],
                default="U",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="mlmodel",
            name="license_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="mlmodel",
            name="low_resource",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Don't know")],
                default="U",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="mlmodel",
            name="output_length",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="mlmodel",
            name="paper",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="mlmodel",
            name="website",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="mlmodel",
            name="year",
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
