# Generated by Django 4.2.20 on 2025-05-22 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genmodels", "0007_remove_mlmodel_interactions_mlmodel_output_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mlmodel",
            name="is_free",
            field=models.CharField(
                choices=[
                    ("Y", "Yes"),
                    ("N", "No"),
                    ("B", "Yes and No, depending on the plan"),
                    ("U", "Not known"),
                ],
                default="U",
                max_length=1,
            ),
        ),
    ]
