# Generated by Django 4.2.20 on 2025-06-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genmodels', '0008_alter_mlmodel_is_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='identifier',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
