# Generated by Django 4.2.20 on 2025-06-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genmodels', '0009_alter_mlmodel_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='guide',
            field=models.TextField(blank=True),
        ),
    ]
