# Generated by Django 4.2.20 on 2025-06-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genmodels', '0010_mlmodel_guide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='guide',
            field=models.TextField(blank=True, help_text='This field renders Markdown'),
        ),
    ]
